---
pool: devpool  

trigger: 
  - master
resources:
  repositories:
    - repository: azuredevops
      endpoint: github.com_srinudammalapati
      ref: 'refs/heads/master'
      name: srinudammalapati/azuredevops
      type: githu
stages:
  - template: azuredevopstemplate.yaml@azuredevops
    parameters: 
      goal: package
      jdkversionoption: "1.11"
      jdkdirectory: "/usr/lib/jvm/java-11-openjdk-amd64/"
  